replicaCount: 1

image:
  repository: 437537529252.dkr.ecr.us-east-1.amazonaws.com/scorecheck-backend
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8000

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi

env:
  SPORTS_DATA_SOURCE: espn
  DATABASE_URL: ""
  SCORECHECK_SEASON: "2025"
  SCORECHECK_NBA_SEASON: "2025"
  SCORECHECK_NHL_SEASON: "2025"
  SCORECHECK_MLB_SEASON: "2026"

database:
  existingSecretName: scorecheck-backend-db
  existingSecretKey: DATABASE_URL
